
module.exports = {
  'URLs': {
  },
  'ActionTypes': {
    QUERY_HASHTAG_DEF: 'QUERY_HASHTAG_DEF',
    SUBMIT_HASHTAG_DEF: 'SUBMIT_HASHTAG_DEF',
    QUERY_HASHTAG_SUCCESS: 'QUERY_HASHTAG_SUCCESS',
    QUERY_HASHTAG_FAILED: 'QUERY_HASHTAG_FAILED',
    SUBMIT_HASHTAG_SUCCESS: 'SUBMIT_HASHTAG_SUCCESS',
    SUBMIT_HASHTAG_FAILED: 'SUBMIT_HASHTAG_FAILED',
    QUERY_HASHTAG_TWEETS: 'QUERY_HASHTAG_TWEETS',
    QUERY_MORE_HASHTAG_TWEETS: 'QUERY_MORE_HASHTAG_TWEETS',
    QUERY_HASHTAG_TWEETS_SUCCESS: 'QUERY_HASHTAG_TWEETS_SUCCESS',
    QUERY_HASHTAG_TWEETS_FAILED: 'QUERY_HASHTAG_TWEETS_FAILED'
  },
  'RegExp': {
  },
  'ErrorTypes': {
    SUBMIT_HASHTAG_ERROR: 'SUBMIT_HASHTAG_ERROR',
    QUERY_HASHTAG_TWEETS_SUCCESS: 'QUERY_HASHTAG_TWEETS_SUCCESS',
    QUERY_HASHTAG_TWEETS_FAILED: 'QUERY_HASHTAG_TWEETS_FAILED'
  },
  'ErrorMessages': {
    SUBMIT_HASHTAG_ERROR: 'Server error: please try again later.'
  },
  'Parameters': {
    RESULT_TYPE_RECENT: "recent",
    RESULT_TYPE_POPULAR: "popular"
  }
};
